name: Coverage
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-python@v5
        with: { python-version: "3.10", cache: pip }

      - name: System deps (mlpack)
        run: |
          sudo apt-get update
          sudo apt-get install -y libmlpack-dev

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install faiss-cpu
          pip install -e packages/blockingpy-core[dev]
          pip install pytest-cov coverage

      - name: Test CPU
        env:
          COVERAGE_FILE: .coverage.cpu
        run: |
          pytest --ignore=tests/test_gpu_faiss.py \
                --cov=blockingpy --cov-branch --cov-report=term-missing

      - name: Test GPU (mock)
        env:
          BPY_GPU_ONLY: "1"
          BPY_GPU_MOCK: "1"
          PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
          COVERAGE_FILE: .coverage.gpu_mock
        run: |
          pytest tests/test_gpu_faiss.py \
            --cov=blockingpy.gpu_faiss_blocker --cov-branch --cov-report=term-missing

      - name: Combine + XML
        run: |
          coverage combine .coverage.cpu .coverage.gpu_mock
          coverage xml -o coverage.xml
          coverage report -m

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  
          files: coverage.xml
          flags: cpu,gpu-mock
          fail_ci_if_error: true
