name: Lint and Type Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: lint-mypy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install uv
        run: python -m pip install -U pip uv

      - name: Create venv and install tools
        run: |
          uv venv
          uv pip install ruff mypy "pandas-stubs>=2.2,<3" types-pytz==2025.2.0

      - name: Ruff (format check + lint)
        run: |
          uv run ruff format --check .
          uv run ruff check .

      - name: MyPy (type check)
        run: uv run mypy packages/blockingpy-core
