name: Lint and Type Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: lint-mypy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install uv
        run: |
          python -m pip install -U pip uv

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ runner.os }}-py310-${{ hashFiles('pyproject.toml', '**/pyproject.toml') }}
          restore-keys: |
            uv-${{ runner.os }}-py310-

      - name: Create venv and install dependencies
        run: |
          uv venv
          uv pip install -e ".[dev]"

      - name: Ruff (format check + lint)
        run: |
          uv run ruff format --check .
          uv run ruff check .

      - name: MyPy (type check)
        run: |
          uv run mypy packages/blockingpy-core