name: Publish to PyPI

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine tomli

      - name: Verify version sync
        run: |
          python - <<'PY'
          import tomli, pathlib
          core = tomli.loads(pathlib.Path("packages/blockingpy-core/pyproject.toml").read_text("utf-8"))["tool"]["poetry"]["version"]
          cpu  = tomli.loads(pathlib.Path("packages/blockingpy/pyproject.toml").read_text("utf-8"))["tool"]["poetry"]["version"]
          gpu  = tomli.loads(pathlib.Path("packages/blockingpy-gpu/pyproject.toml").read_text("utf-8"))["tool"]["poetry"]["version"]
          assert core == cpu == gpu, f"Version mismatch: core={core}, blockingpy={cpu}, blockingpy-gpu={gpu}"
          print("Version:", core)
          PY

      - name: Build core
        run: python -m build -o packages/blockingpy-core/dist packages/blockingpy-core

      - name: Build blockingpy (meta CPU)
        run: python -m build -o packages/blockingpy/dist packages/blockingpy

      - name: Build blockingpy-gpu (meta GPU)
        run: python -m build -o packages/blockingpy-gpu/dist packages/blockingpy-gpu

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload \
            packages/blockingpy-core/dist/* \
            packages/blockingpy/dist/* \
            packages/blockingpy-gpu/dist/*
